### ISSUE TITLE
[Question] How to make pam-beacon optional?

### ISSUE THREAD

**Issue by AdrianVovk** [muesli/pam-beacon#1]
> Careful: if your bluetooth beacon isn't discoverable, you will lock yourself out
of your system! 

What line should I append to the pam configuration in order to make the beacon a secondary form of authentication. In other words, how could I make it so I can log in with my password or the beacon?

**Comment by muesli** [comment]
You can edit `/etc/pam.d/system-auth-beaon` and change the word `required` to `sufficient`. Careful though, the mere presence of this bluetooth device will make anyone able to unlock your system, of course.

Make sure you include `system-auth-beacon` _before_ the pam_unix.so check.
