### ISSUE TITLE
Update go module location

### ISSUE THREAD

**Issue by bjmd** [muesli/pam-beacon#6]
Hi, can you please update the following to reflect the new location of the `btmgmt` code?

```
- "github.com/muka/go-bluetooth/linux/btmgmt"
+ "github.com/muka/go-bluetooth/hw/linux/btmgmt"
```

Also `"github.com/muka/go-bluetooth/emitter"` seems to not exist anymore?

I can't raise a PR for you, otherwise I would.

**Comment by muesli** [comment]
Thank you! Fixed in master.
